import { Inter } from "next/font/google";
import Head from "next/head";

import { Hero, SplitWithImage, ThreeTierPricing } from "@/modules/home";
import LargeWithNewsletter from "@/modules/layouts/footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <SplitWithImage />
        <ThreeTierPricing />
      </main>
      <LargeWithNewsletter />
    </>
  );
}
